services:
  postgres:
    container_name: career-manager
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: career-manager
      PGDATA: /data/postgres
